version: '3.8'

services:
  app:
    build: .
    container_name: netflix-app
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: netflix-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: netflix
    ports:
      - "3306:3306"